server:
  servlet:
    context-path: /check
  port: 8080
spring:
  jackson:
    default-property-inclusion: non_null
  redis:
    port: 6379
    host: 127.0.0.1
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/check?characterEncoding=utf-8&useSSL=false
mybatis:
      configuration:
          map-underscore-to-camel-case: true
      mapper-locations: mybatis/**/*Mapper.xml